### PR TITLE
Adding Student review section.

### PR DESCRIPTION
**Pull request by Yaser-123**
Issue #6 
Adding this section using
HML
CSS
JS
making it responsive and adding rating to it

https://github.com/MastanSayyad/Visual-Sort/assets/140265777/25b6d9df-bf01-4267-b14e-a2718e5f7786

### CODE REVIEW

**Comment by MastanSayyad** [comment]
@Yaser-123 looks great, thank you!
you can look for other issues keep contributing!!

**Comment by Yaser-123** [comment]
Yes I will look, have u added my points in scoreboard???

**Comment by MastanSayyad** [comment]
yes i did

**Comment by Yaser-123** [comment]
Thanks

**Pull request merged**
