### PR TITLE
made-the-visualization-page-responsive

### PR DESCRIPTION
**Pull request by Ayushswirlon**
## Issue number
#95 

Issue fixes: #95 

## Screenshots (if any)
image

### CODE REVIEW

**Review by MastanSayyad — APPROVED** [review]
Looks great, let's wait to get reviewed by the collaborator!

**Review by RadhikaMalpani1702 — CHANGES_REQUESTED** [review]
"The visulizers bar are already appearing without submitting array numbers, Please fix that" @Ayushswirlon

**Comment by Ayushswirlon** [comment]
It's a default array for sorting if you don't like it will remove it 👍

**Comment by RadhikaMalpani1702** [comment]
@Ayushswirlon "If it is on purpose then it's okay, no need to change"

**Review by RadhikaMalpani1702 — APPROVED** [review]

**Pull request merged**
