### PR TITLE
Added About Us Section

### PR DESCRIPTION
**Pull request by pandey22**
-Added an **About Us** Section 
- **Linked** it to the nav bar and footer

image

### CODE REVIEW

**Comment by MastanSayyad** [comment]
Please resolve the conflicts @pandey22

**Comment by MastanSayyad** [comment]
@pandey22 

also please this issue:


https://github.com/MastanSayyad/Visual-Sort/assets/101971980/5cf29c10-061a-4c82-9bf1-406ca7f07907

**Comment by pandey22** [comment]
Sure  i'll fix both the issues in a while

**Comment by MastanSayyad** [comment]
image

image


Fix this @pandey22

**Pull request closed without merging**
