### PR TITLE
Add Loader to Website

### PR DESCRIPTION
**Pull request by Yaser-123**
Email :- 1ammar.yaser@gmail.com

issue #78 

I propose adding a loader to the Visual Sort website to improve user experience during sorting operations. This enhancement will inform users that a process is ongoing, especially during longer sorting times.

Title: Loading Indicator
Description: Implement a loading spinner or progress bar that appears when the sorting process starts and disappears upon completion. This feature will enhance the user experience by providing visual feedback during operations.
Features:
Loading spinner or progress bar
Display during sorting process initialization and execution
Hide once sorting is complete

https://github.com/MastanSayyad/Visual-Sort/assets/140265777/3c9a7769-10c6-4913-8dd2-ca809ee84a7c

### CODE REVIEW

**Comment by MastanSayyad** [comment]
The preloader looks good but it should work across all the pages

add the preloader in all HTML files

**Comment by Yaser-123** [comment]
Ok

**Comment by Yaser-123** [comment]
Done merge it to main branch

**Review by MastanSayyad — APPROVED** [review]
Approved

**Pull request merged**
