### PR TITLE
Only Quick Sort Page

### PR DESCRIPTION
**Pull request by AkshatPandey-2004**
Label: Bonus

Email id: akshatpandey26.2004@gmail.com

### CODE REVIEW

**Review by MastanSayyad — CHANGES_REQUESTED** [review]
@AkshatPandey-2004 I cant redirect to the pages please add the respective navlinks

**Comment by MastanSayyad** [comment]
@AkshatPandey-2004 I think you added only in index.html navbar as when i go to quick sort page and try redirect from there to other sorting pages then it shows error 

please ensure you update the links in each pages navbar so that users can easily access to them

**Comment by MastanSayyad** [comment]
It is not possible as per the guidelines, one PR can only get max points 50 only!

**Comment by MastanSayyad** [comment]
I have to assign the score as per the number of PR merged with their assign scores, i have to update the score report to the moderators, that's why I need PR numbers for repsective scores @AkshatPandey-2004 

I already told you to create individual PRs for each page and i will only assign 40 points each and at last Two Algorithms PRs i will assign 50 points!! ( as you know at start you were only asking for Hard label 20 points but I have increase it to Bonus 40 points and for last two PRs 50-50 bonus points)

**Comment by MastanSayyad** [comment]
If you can add Footers and Scroll to top button ( which already exists in index.html)  then i can assign 50 points to each PR ( as a developer we must ensure consistency across all the pages to look more real and everything at one place) @AkshatPandey-2004

**Review by RadhikaMalpani1702 — APPROVED** [review]

**Pull request merged**
