### PR TITLE
Add AI Chatbot Feature to Enhance User Engagement on Study Website

### PR DESCRIPTION
**Pull request by Yaser-123**
Email :- 1ammar.yaser@gmail.com

Isse #26 

We propose the addition of an AI-powered chatbot to our study website to enhance user engagement, provide instant support, and improve overall user experience. This chatbot will assist users by answering common questions, guiding them through the site, offering study tips, and potentially integrating with existing educational resources.
Objectives:
1.Instant User Support
2.Enhanced User Experience
3.Resource Integration

https://github.com/MastanSayyad/Visual-Sort/assets/140265777/3bccee48-f60c-42a8-b4b5-080bdce6dc2f

### CODE REVIEW

**Review by MastanSayyad — CHANGES_REQUESTED** [review]
@Yaser-123 It is not convenient

Can you add chatbot like this


https://github.com/MastanSayyad/Visual-Sort/assets/101971980/0d58bce8-2879-4646-98c6-c49e1e9f53b5

**Comment by Yaser-123** [comment]
Yeah, I tried it but I can't do it I Don't know why
Can u make pr of this, and assign the enhancement to other member who can do it

**Comment by Yaser-123** [comment]
And replace the API_KEY in html and css or else it won't work

**Review by MastanSayyad — COMMENTED** [review]
Approved

**Pull request merged**
