### PR TITLE
Visual sort tour guide

### PR DESCRIPTION
**Pull request by Ayushswirlon**
## Description

had added a complete tour guide for beginners to get how the visualizer works
## Issue number
#74 

Issue fixes: #74 

## Screenshots (if any)

Screenshot 2024-07-07 111854
Screenshot 2024-07-07 111907
Screenshot 2024-07-07 111921
Screenshot 2024-07-07 111931
Screenshot 2024-07-07 111941
Screenshot 2024-07-07 111954
Screenshot 2024-07-07 112007

### CODE REVIEW

**Comment by MastanSayyad** [comment]
@Ayushswirlon loved the work !!

can you please add skip button in red color besides next button in guide so that people who revisited can skip it!

**Comment by Ayushswirlon** [comment]
Done bro review it again

**Review by MastanSayyad — CHANGES_REQUESTED** [review]
@Ayushswirlon Background should have little shadow when the guide pops up

**Like this one, previously it had**

image

**But now it is showing like this:**

image



The focus should be on the guide pop msg

**Comment by Ayushswirlon** [comment]
Okk will check and submit till tomorrow

**Pull request merged**
