### PR TITLE
Feature

### LINKED ISSUE #128: [FEATURE] New Contact us Page
**Description**
Making s new Contact Us Page respective to current design theme

**Use Case**
(Use cases and benefits)

**Screenshots**
(Screenshots of the issue or reference)

**Additional Context**
(Any other context about the problem)

### LINKED ISSUE #129: [FEATURE] Hiding Data
**Description**
Hiding API info inside .env file

**Use Case**
(Use cases and benefits)

**Screenshots**
(Screenshots of the issue or reference)

**Additional Context**
(Any other context about the problem)

### LINKED ISSUE #131: [FEATURE] Custom scrollbar
**Description**
As the website bg is white, it is difficult to see where you are on the page

**Use Case**
I can add a custom purple scrollbar

**Screenshots**
(Screenshots of the issue or reference)

**Additional Context**
(Any other context about the problem)

### PR DESCRIPTION
**Pull request by Mehak-Mattoo**
## Description

1. Added a new custom scrollbar
2. Added a new contact us page
3. Created a gitignore and .env file for data hiding

## Issue number

issue closes #131 , closes #129  and closes #128 

## Screenshots (if any)
ta

### CODE REVIEW

**Review by RadhikaMalpani1702 — CHANGES_REQUESTED** [review]
image

You did't add the custome scrollbar in these pages

**Review by RadhikaMalpani1702 — CHANGES_REQUESTED** [review]
@Mehak-Mattoo Create .env.example file which should have the API Keys templet so that it can show what necessary environment variables and API Keys are needed to execute the chatbot

**Comment by Mehak-Mattoo** [comment]
I tried adding the custom scrollbar to algorithm pages, but then 2 scrollbar starts rendering on the page, as the content alignment was not good there so there was  a scrollbar everpresent.

I'll add an env.example and make the changes

**Comment by MastanSayyad** [comment]
@Mehak-Mattoo Yeah no issues

**Comment by MastanSayyad** [comment]
@Mehak-Mattoo Create an empty pull request so that I can add more bonus points to as you have solved all issues in one PR I can only assign you 50 points

**Comment by Mehak-Mattoo** [comment]
Okay

**Pull request merged**
