### PR TITLE
Updated Greeting Workflows

### LINKED ISSUE #110: [BUG] Fix workflows
**Description**
(Description about the issue)
Fix the github greeting workflows

**Use Case**
(Use cases and benefits)

**Screenshots**
(Screenshots of the issue or reference)

**Additional Context**
(Any other context about the problem)

### PR DESCRIPTION
**Pull request by deepesh611**
## Description

I have updated the Issue Greeting and the PR thank bot

## Issue number

Issue fixes #110 

## Screenshots (if any)

Issue
image

PR (Opened & Merged)
image

### CODE REVIEW

**Comment by MastanSayyad** [comment]
Provide your email im discord channel to assign points @deepesh611

**Comment by MastanSayyad** [comment]
@deepesh611 I dont think the worlflow is working

**Comment by deepesh611** [comment]
Try creating a new test issue

**Comment by deepesh611** [comment]
@MastanSayyad, pls make sure that your repo settings are correctly configured to allow the use of workflows

**Comment by MastanSayyad** [comment]
> @MastanSayyad, pls make sure that your repo settings are correctly configured to allow the use of workflows

what configurations are required for workflows?

**Comment by deepesh611** [comment]
> > @MastanSayyad, pls make sure that your repo settings are correctly configured to allow the use of workflows
> 
> what configurations are required for workflows?

Is it possible to add me as a Collab ?
I will set the things 4 u, then u can remove it from Collab, and only let me be a contri.

**Comment by MastanSayyad** [comment]
its fine the event is going to end anyways

**Comment by deepesh611** [comment]
> its fine the event is going to end anyways

still, it's good to know what the actual issue was. It comes handy for later contributions

**Comment by deepesh611** [comment]
> Provide your email im discord channel to assign points @deepesh611

deepeshvcd6273@gmail.com

**Comment by MastanSayyad** [comment]
> > Provide your email im discord channel to assign points @deepesh611
> 
> [deepeshvcd6273@gmail.com](mailto:deepeshvcd6273@gmail.com)

Already Assigned!

**Comment by deepesh611** [comment]
> > its fine the event is going to end anyways
> 
> still, it's good to know what the actual issue was. It comes handy for later contributions

..

**Pull request merged**
