### PR TITLE
dark mode done

### PR DESCRIPTION
**Pull request by kratik1237**
## Issue number

Issue fixes: #12

### CODE REVIEW

**Comment by kratik1237** [comment]
@MastanSayyad #98 check

**Comment by kratik1237** [comment]
done ??? @MastanSayyad

**Comment by MastanSayyad** [comment]
yes @kratik1237

**Comment by kratik1237** [comment]
it is hard issue... only 20 points ?? @MastanSayyad

**Comment by MastanSayyad** [comment]
Easy = 5 points
Medium = 10 points
Hard = 20 points

**Comment by kratik1237** [comment]
okay thank you, i think 40 points @MastanSayyad

**Pull request merged**
