### PR TITLE
Add counting sort in the list of sorting techniques

### PR DESCRIPTION
**Pull request by kratik1237**
## Description

Add counting sort in the list of sorting techniques

## Issue number
#14 

Issue fixes: #14 
Screenshot (70)
Screenshot (71)

### CODE REVIEW

**Comment by kratik1237** [comment]
pls review the PR #113 for the issue #14 @MastanSayyad

**Review by RadhikaMalpani1702 — APPROVED** [review]

**Comment by MastanSayyad** [comment]
@kratik1237 The page  has so many bugs

**Comment by MastanSayyad** [comment]
The PR is incomplete:

- The footer is not matching to website design theme it is not aligned
- The navbar is not same as home page, especially the dropdown
- The page is not responsive 
- You didn't add counting sort card in sorting visluzier section also you didn't create a visualizer in visual.html
- You didn't add section for counting sort in algotthms section with its working gif and pesudo code
- You didn't integrated scroll to top button and AI chatbot like other sorting pages!

**Comment by kratik1237** [comment]
@MastanSayyad i can fix it wait.

**Comment by MastanSayyad** [comment]
Fix it in other PR @kratik1237

**Comment by MastanSayyad** [comment]
I will merge this for now

**Comment by kratik1237** [comment]
Okay ,but it is my last pr @MastanSayyad

**Comment by MastanSayyad** [comment]
I will merge this for now, make another PR, if this one is your last PR then I can add 50 points only if you are okay with it then fix it in This PR

**Comment by kratik1237** [comment]
Okay I will try to fix @MastanSayyad

**Comment by kratik1237** [comment]
yes @MastanSayyad

**Pull request merged**
