### PR TITLE
I add the privacy policy

### PR DESCRIPTION
**Pull request by kratik1237**
Closed issue #58 .
I Create Privacy Policy Page and link it to the footer link.

Create Privacy Policy Page
Link it to Footer
Page must be Responsive

I follow all three points.

### CODE REVIEW

**Review by MastanSayyad — CHANGES_REQUESTED** [review]
image


@kratik1237 

It doesnt look like a privacy policy page 


The page should like as following:

image

**Comment by kratik1237** [comment]
Okay I do this @MastanSayyad

**Comment by kratik1237** [comment]
@MastanSayyad  i commit the pulll request #70

**Review by MastanSayyad — CHANGES_REQUESTED** [review]
Hey @kratik1237 

i told you to take the reference of the image to create a privacy page like that one but you just created the same as it is page 
please create a page for "visual sort" website

image

please take the "REFERENCE" of this page to create a one for our website!!

https://nacto-care.vercel.app/privacypolicy

Create like above one for "Visual Sort" Website 


also you have broke the footer

image


please fix it!

**Comment by kratik1237** [comment]
Sorry for this misunderstanding, I will fix it tomorrow @MastanSayyad

**Comment by kratik1237** [comment]
@MastanSayyad I completed the privacy policy. please check #70

**Comment by MastanSayyad** [comment]
@kratik1237 looks good

**Comment by kratik1237** [comment]
Thank you.@MastanSayyad 
Can you give me points?

**Comment by MastanSayyad** [comment]
Obviously @kratik1237

**Comment by kratik1237** [comment]
Thank you so much.@MastanSayyad

**Pull request merged**
