### PR TITLE
Added the comb sort algorithm

### PR DESCRIPTION
**Pull request by aadium**
1. Added the comb sort algorithm
2. Updated the navbar to use the visual.html page.

### CODE REVIEW

**Comment by MastanSayyad** [comment]
@aadium pls mention your mail in discord to assign scores

**Comment by aadium** [comment]
Didcord username: aadixum

**Comment by MastanSayyad** [comment]
@aadium no results found

Have you mentioned yourself in contributors list??

**Comment by MastanSayyad** [comment]
@aadium pls do it first, then only I can assign points for you as it will show participant is not available

**Comment by aadium** [comment]
Where can I find that list?

**Comment by MastanSayyad** [comment]
in VSoC discrod channels 

https://discord.com/channels/1234877876382208082/1250482526175236128

**Comment by aadium** [comment]
I am not in vsoc

**Comment by MastanSayyad** [comment]
@aadium Okay its fine

**Comment by MastanSayyad** [comment]
Thank you for the contribution!!

**Pull request merged**
