### PR TITLE
Added contributor.html into the website

### PR DESCRIPTION
**Pull request by Tejashri-Taral**
Hey @MastanSayyad,
I have added Contributors Page into the website.
****Video****

https://github.com/user-attachments/assets/f6c2786f-5879-4df3-ba03-a330fa960caf

Please take a look and review it.

### CODE REVIEW

**Review by MastanSayyad — COMMENTED** [review]
Great, thank you!

**Review by MastanSayyad — APPROVED** [review]

**Comment by Tejashri-Taral** [comment]
@MastanSayyad Please add label hacktoberfest-accepted

**Comment by MastanSayyad** [comment]
@Tejashri-Taral sorry I forgot to add, Hacktoberfest takes 7 days to review each PR, you can see it in your Hacktoberfest profile (it updates each 15 mins)

**Comment by Tejashri-Taral** [comment]
Yeah, I saw that Thanks for letting me know!

**Pull request merged**
